patterns:
  deny:
    - regex: '^$CI_MERGE_REQUEST_PROJECT_URL/(-/)?merge_requests/$CI_MERGE_REQUEST_IID$'
      message: Commit message must not contain a link to its own merge request
    - regex: '^[^:]+: [a-z]'
      message: "Commit message subject should be properly Capitalized. E.g. 'window: Marginalize extradicity'"
      where: subject
    - regex: '^\S*\.[ch]:'
      message: Commit message subject prefix should not include .c, .h, etc.
      where: subject
    - regex: '^[Cc]lose[sd]?:?\s*#[0-9]+'
      message: Closes instructions must be a full link
    - regex: '^[Ff]ix(e[sd]?)?:?\s*(#[0-9]+|https://)'
      message: \"Fixes\" should be used with commits, use \"Closes\" for issues

